// ini nama orang
#include <iostream.h>
#include <conio.h>
void main ()
{
clrscr() ;
cout<<"AAAAAAAAA     GGGGGGGGGGG     UU     UU\n";
cout<<"AAAAAAAAA     GGGGGGGGGGG     UU     UU"<<endl;
cout<<"AA     AA     GG              UU     UU"<<endl;
cout<<"AA     AA     GG   GGGGGG     UU     UU"<<endl;
cout<<"AAAAAAAAA     GG   GGGGGG     UU     UU"<<endl;
cout<<"AA     AA     GG       GG     UU     UU"<<endl;
cout<<"AA     AA     GGGGGGGGGGG     UUUUUUUUU"<<endl;
cout<<"AA     AA     GGGGGGGGGGG     UUUUUUUUU"<<endl;
getch();
}
