// nama saya
#include <iostream.h>
#include <conio.h>

void main()
{
clrscr;
cout<<"AAAAAAAAA     NN              NN     AAAAAAAAA\n";
cout<<"AAAAAAAAA     NN NN           NN     AAAAAAAAA"<<endl;
cout<<"AA     AA     NN    NN        NN     AA     AA"<<endl;
cout<<"AA     AA     NN       NN     NN     AA     AA"<<endl;
cout<<"AAAAAAAAA     NN         NN   NN     AAAAAAAAA"<<endl;
cout<<"AA     AA     NN           NN NN     AA     AA"<<endl;
cout<<"AA     AA     NN              NN     AA     AA"<<endl;
cout<<"AA     AA     NN              NN     AA     AA"<<endl;
getch ();
}
